// Generated by training/train_edge.py; do not edit manually.
#pragma once
#include <stdint.h>
#define SKYG_E1_FEATURES 15
#define SKYG_E1_NODES 37
static const float SKYG_E1_MEDIAN[15] = {27.059441f, 1006.3633f, 70.302113f, 0f, 0.0008706243f, 0f, 27.079f, 1006.3641f, 70.302325f, 0.25338429f, 0.11497395f, 1.0847782f, 0f, 0f, 0f};
static const int16_t SKYG_E1_LEFT[37] = {1, 2, 3, 4, -1, 6, -1, -1, -1, 10, -1, 12, 13, -1, -1, -1, 17, 18, 19, -1, 21, -1, -1, -1, 25, 26, -1, 28, -1, -1, 31, 32, -1, -1, 35, -1, -1};
static const int16_t SKYG_E1_RIGHT[37] = {16, 9, 8, 5, -1, 7, -1, -1, -1, 11, -1, 15, 14, -1, -1, -1, 24, 23, 20, -1, 22, -1, -1, -1, 30, 27, -1, 29, -1, -1, 34, 33, -1, -1, 36, -1, -1};
static const int8_t SKYG_E1_FEATURE[37] = {9, 9, 8, 4, -2, 1, -2, -2, -2, 1, -2, 10, 4, -2, -2, -2, 11, 5, 5, -2, 1, -2, -2, -2, 10, 4, -2, 4, -2, -2, 3, 5, -2, -2, 3, -2, -2};
static const float SKYG_E1_THRESHOLD[37] = {0.078905541f, 0.040787814f, 75.90361f, -0.056631658f, -2f, 1006.7558f, -2f, -2f, -2f, 1006.3857f, -2f, 0.12945931f, 0.037315207f, -2f, -2f, -2f, 0.26404828f, 0.019158497f, -0.013009358f, -2f, 1004.9006f, -2f, -2f, -2f, 0.037481887f, -0.00025619313f, -2f, 0.00047966812f, -2f, -2f, 1.0220302f, 17.92049f, -2f, -2f, 5.4204781f, -2f, -2f};
static const uint8_t SKYG_E1_LEAF[37] = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1};

static inline uint8_t skyguard_e1_predict(float feature[SKYG_E1_FEATURES]) {
  for (uint8_t i=0; i<SKYG_E1_FEATURES; ++i) if (__builtin_isnan(feature[i])) feature[i]=SKYG_E1_MEDIAN[i];
  int16_t node=0;
  while (SKYG_E1_LEFT[node] >= 0) {
    int8_t f=SKYG_E1_FEATURE[node];
    node=(feature[f] <= SKYG_E1_THRESHOLD[node]) ? SKYG_E1_LEFT[node] : SKYG_E1_RIGHT[node];
  }
  return SKYG_E1_LEAF[node];
}
