"""Train and export the compact ESP32 SkyGuard E1 model.

The C header is deliberately dependency-free: it needs no TensorFlow Lite or
dynamic allocation.  Median fill values must be applied before inference.
"""
from __future__ import annotations
import json
from pathlib import Path
import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import precision_recall_fscore_support, roc_auc_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

ROOT = Path(__file__).resolve().parents[1]
DATA, MODELS, FIRMWARE = ROOT / "data", ROOT / "models", ROOT / "edge" / "esp32"
FEATURES = ["temperature", "pressure", "humidity", "temperature_delta", "pressure_delta", "humidity_delta",
            "temperature_roll_mean", "pressure_roll_mean", "humidity_roll_mean", "temperature_roll_std",
            "pressure_roll_std", "humidity_roll_std", "temperature_missing", "pressure_missing", "humidity_missing"]


def score(name: str, model, x_train, y_train, x_val, y_val) -> tuple[dict, object]:
    model.fit(x_train, y_train)
    pred = model.predict(x_val)
    prob = model.predict_proba(x_val)[:, 1]
    p, r, f, _ = precision_recall_fscore_support(y_val, pred, average="binary", zero_division=0)
    nodes = getattr(getattr(model, "tree_", None), "node_count", None)
    # 4 x int32 child/feature/class plus float threshold ≈ 20 bytes per node.
    return {"candidate": name, "precision": round(float(p), 4), "recall": round(float(r), 4), "f1": round(float(f), 4),
            "roc_auc": round(float(roc_auc_score(y_val, prob)), 4), "nodes": nodes,
            "estimated_model_bytes": (nodes or 0) * 20}, model


def c_array(name: str, values, typ: str) -> str:
    values = list(values)
    return f"static const {typ} {name}[{len(values)}] = {{" + ", ".join(str(v) for v in values) + "};\n"


def export_header(tree: DecisionTreeClassifier, medians: np.ndarray) -> int:
    t = tree.tree_; n = t.node_count
    feature = [int(v) for v in t.feature]
    threshold = [f"{float(v):.8g}f" for v in t.threshold]
    left, right = [int(v) for v in t.children_left], [int(v) for v in t.children_right]
    # class 1 if anomaly has at least as many weighted examples in leaf
    leaf_class = [int(v[0][1] >= v[0][0]) for v in t.value]
    text = "// Generated by training/train_edge.py; do not edit manually.\n#pragma once\n#include <stdint.h>\n"
    text += f"#define SKYG_E1_FEATURES {len(FEATURES)}\n#define SKYG_E1_NODES {n}\n"
    text += c_array("SKYG_E1_MEDIAN", [f"{x:.8g}f" for x in medians], "float")
    text += c_array("SKYG_E1_LEFT", left, "int16_t") + c_array("SKYG_E1_RIGHT", right, "int16_t")
    text += c_array("SKYG_E1_FEATURE", feature, "int8_t") + c_array("SKYG_E1_THRESHOLD", threshold, "float")
    text += c_array("SKYG_E1_LEAF", leaf_class, "uint8_t")
    text += """
static inline uint8_t skyguard_e1_predict(float feature[SKYG_E1_FEATURES]) {
  for (uint8_t i=0; i<SKYG_E1_FEATURES; ++i) if (__builtin_isnan(feature[i])) feature[i]=SKYG_E1_MEDIAN[i];
  int16_t node=0;
  while (SKYG_E1_LEFT[node] >= 0) {
    int8_t f=SKYG_E1_FEATURE[node];
    node=(feature[f] <= SKYG_E1_THRESHOLD[node]) ? SKYG_E1_LEFT[node] : SKYG_E1_RIGHT[node];
  }
  return SKYG_E1_LEAF[node];
}
"""
    FIRMWARE.mkdir(parents=True, exist_ok=True); (FIRMWARE / "edge_model.h").write_text(text, encoding="utf-8")
    return len(text.encode("utf-8"))


def main() -> None:
    MODELS.mkdir(exist_ok=True)
    df = pd.read_csv(DATA / "edge_training.csv").sort_values("timestamp")
    split = int(len(df) * .8); train, val = df.iloc[:split], df.iloc[split:]
    medians = train[FEATURES].median().fillna(0)
    x_train, x_val = train[FEATURES].fillna(medians), val[FEATURES].fillna(medians)
    y_train, y_val = train.label.astype(int), val.label.astype(int)
    candidates = [("logistic_regression", LogisticRegression(max_iter=300, class_weight="balanced")),
        *[(f"decision_tree_depth_{d}", DecisionTreeClassifier(max_depth=d, min_samples_leaf=20, class_weight="balanced", random_state=42)) for d in range(3, 7)]]
    results=[]; fitted={}
    for name, model in candidates:
        result, fitted_model = score(name, model, x_train, y_train, x_val, y_val); results.append(result); fitted[name]=fitted_model
    # Logistic regression is a benchmark only. The C firmware uses the highest
    # F1 decision tree; all candidates are below a 1 KB estimated model budget.
    tree_results=[r for r in results if r["candidate"].startswith("decision_tree")]
    chosen=max(tree_results, key=lambda r: (r["f1"], r["recall"], -r["estimated_model_bytes"]))
    model=fitted[chosen["candidate"]]
    header_bytes=export_header(model, medians.to_numpy())
    joblib.dump({"model":model,"features":FEATURES,"medians":medians.to_dict(),"version":"E1-1.0.0"}, MODELS/"edge_e1.joblib")
    payload={"selection_rule":"highest validation F1 among deployable (< 1 KB estimated) decision trees", "chosen":chosen,
             "candidates":results, "generated_header_bytes":header_bytes,
             "working_ram_bytes": len(FEATURES)*4 + 64, "assumptions":"model arrays are flash-resident constants; values are approximate"}
    (MODELS/"edge_benchmark.json").write_text(json.dumps(payload,indent=2), encoding="utf-8")
    print(json.dumps(payload, indent=2))


if __name__ == "__main__": main()
